import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, BarChart3, ChevronDown, Clock3, Database, Download, Gauge, Layers3, Loader2, RefreshCw, SlidersHorizontal, Sparkles, Wifi, X } from "lucide-react";
import { CandlestickChart, RrgChart, type MarketRow } from "@/components/MarketCharts";

type TimeframeKey = "1m" | "5m" | "15m" | "30m" | "1h" | "1d" | "1wk";
type UniverseKey = "SECTORS" | "INDUSTRIES" | keyof typeof SECTOR_ETFS;
type MarketSeries = { timestamps: number[]; open: number[]; high: number[]; low: number[]; close: number[] };
type InstrumentMetadata = { name: string; exchange?: string; currency?: string; price?: number | null; previousClose?: number | null };
type Dataset = Record<string, MarketSeries>;
type RrgPoint = { x: number; y: number; ts: number };
type RrgAsset = { ticker: string; label: string; points: RrgPoint[] };
type Snapshot = { ts: number; assets: RrgAsset[] };

const SECTOR_ETFS: Record<string, string> = { XLE: "Energy", XLF: "Financials", XLK: "Technology", XLV: "Health Care", XLI: "Industrials", XLY: "Consumer Discretionary", XLP: "Consumer Staples", XLU: "Utilities", XLRE: "Real Estate", XLB: "Materials", XLC: "Communication Services" };
const INDUSTRY_ETFS: Record<string, string> = { FDN: "Internet", IBB: "Biotechnology", JETS: "Airlines", SMH: "Semiconductors", PBW: "Clean Energy", TAN: "Solar", OIH: "Oil Services", XOP: "Oil & Gas E&P", XME: "Metals & Mining", VNQ: "Real Estate", ITA: "Aerospace & Defense", IGV: "Software", KIE: "Insurance", KRE: "Regional Banks", XRT: "Retail" };
const FALLBACK_HOLDINGS: Record<string, string[]> = { XLE: ["XOM", "CVX", "COP", "WMB", "EOG", "KMI", "MPC", "SLB", "PSX", "OKE"], XLF: ["BRK-B", "JPM", "V", "MA", "BAC", "WFC", "GS", "SPGI", "MS", "C"], XLK: ["NVDA", "MSFT", "AAPL", "AVGO", "ORCL", "PLTR", "AMD", "CSCO", "CRM", "IBM"], XLV: ["LLY", "JNJ", "ABBV", "ABT", "UNH", "MRK", "TMO", "ISRG", "AMGN", "BSX"], XLI: ["GE", "RTX", "CAT", "UBER", "BA", "ETN", "HON", "UNP", "DE", "ADP"], XLY: ["AMZN", "TSLA", "HD", "MCD", "BKNG", "TJX", "LOW", "SBUX", "DASH", "ORLY"], XLP: ["WMT", "COST", "PG", "KO", "PM", "PEP", "MO", "MDLZ", "CL", "TGT"], XLU: ["NEE", "CEG", "SO", "DUK", "VST", "AEP", "SRE", "D", "EXC", "PEG"], XLRE: ["WELL", "PLD", "AMT", "EQIX", "DLR", "O", "SPG", "CCI", "CBRE", "PSA"], XLB: ["LIN", "SHW", "NEM", "ECL", "MLM", "VMC", "APD", "NUE", "FCX", "CTVA"], XLC: ["META", "GOOGL", "GOOG", "NFLX", "EA", "TMUS", "T", "VZ", "TTWO", "DIS"] };
const TIMEFRAMES: Record<TimeframeKey, { label: string; range: string; interval: string }> = { "1m": { label: "1 min", range: "2d", interval: "1m" }, "5m": { label: "5 min", range: "5d", interval: "5m" }, "15m": { label: "15 min", range: "15d", interval: "15m" }, "30m": { label: "30 min", range: "30d", interval: "30m" }, "1h": { label: "1 hour", range: "60d", interval: "1h" }, "1d": { label: "Daily", range: "1y", interval: "1d" }, "1wk": { label: "Weekly", range: "2y", interval: "1wk" } };
const PALETTE = ["#35e08a", "#58a6ff", "#ffcf5c", "#ff6b7c", "#a98bff", "#4de1f0", "#ff9f5b", "#e78bdb", "#8bd3dd", "#c8e26a", "#d0a8ff"];
const SECTOR_COLORS: Record<string, string> = { XLK: "#35e08a", XLC: "#35e08a", XLY: "#35e08a", XLU: "#ff6b7c", XLRE: "#ff6b7c", XLP: "#ff6b7c", XLI: "#ffcf5c", XLB: "#ffcf5c", XLF: "#ffcf5c", XLV: "#58a6ff", XLE: "#58a6ff" };
const colors = { ink: "#edf5ff", muted: "#7f9bb8", bg: "#07111f" };
const REFRESH_MINUTES: Record<TimeframeKey, number> = { "1m": 1, "5m": 5, "15m": 15, "30m": 30, "1h": 60, "1d": 1440, "1wk": 1440 };

function hashColor(ticker: string, universe: UniverseKey) { if (universe === "SECTORS" && SECTOR_COLORS[ticker]) return SECTOR_COLORS[ticker]; let sum = 0; for (const char of ticker) sum = (sum * 31 + char.charCodeAt(0)) % PALETTE.length; return PALETTE[sum]; }
function universeMap(universe: UniverseKey): Record<string, string> { if (universe === "SECTORS") return SECTOR_ETFS; if (universe === "INDUSTRIES") return INDUSTRY_ETFS; return Object.fromEntries((FALLBACK_HOLDINGS[universe] || []).map((ticker) => [ticker, ticker])); }
function benchmarkFor(universe: UniverseKey) { return universe === "SECTORS" || universe === "INDUSTRIES" ? "SPY" : universe; }
function formatEastern(ts: number, withDate = true) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", month: "short", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(new Date(ts * 1000)); const get = (type: string) => parts.find((part) => part.type === type)?.value || ""; return withDate ? `${get("month")} ${get("day")} · ${get("hour")}:${get("minute")} ET` : `${get("hour")}:${get("minute")}`; }
function formatEasternLong(ts: number) { return new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", hour12: true }).format(new Date(ts * 1000)) + " ET"; }
function formatCompact(value: number | undefined) { return value === undefined || !Number.isFinite(value) ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: 2 }); }
function newYorkParts(now = new Date()) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hour: "numeric", minute: "numeric", second: "numeric", weekday: "short", hour12: false }).formatToParts(now); const get = (type: string) => parts.find((part) => part.type === type)?.value || ""; return { weekday: get("weekday"), hour: Number(get("hour")), minute: Number(get("minute")), second: Number(get("second")) }; }
function refreshBucket(timeframe: TimeframeKey, now = new Date()) { const { weekday, hour, minute, second } = newYorkParts(now); const clockMinutes = hour * 60 + minute; if (["Sat", "Sun"].includes(weekday) || clockMinutes < 9 * 60 + 30 || clockMinutes >= 16 * 60) return null; if (timeframe === "1wk" && weekday !== "Mon") return null; const elapsed = clockMinutes - (9 * 60 + 30); const cadence = REFRESH_MINUTES[timeframe]; if (timeframe === "1d" || timeframe === "1wk") return second < 8 && elapsed === 0 ? `${weekday}-${hour}-${minute}` : null; return elapsed % cadence === 0 && second < 8 ? `${weekday}-${hour}-${minute}` : null; }
function rollingMean(values: number[], end: number, size: number) { if (end < size - 1) return null; let total = 0; for (let index = end - size + 1; index <= end; index += 1) total += values[index]; return total / size; }
function buildSnapshots(dataset: Dataset, universe: UniverseKey, metadata: Record<string, InstrumentMetadata>): Snapshot[] { const map = universeMap(universe); const benchmarkSeries = dataset[benchmarkFor(universe)]; if (!benchmarkSeries?.timestamps?.length) return []; const benchmarkClose = new Map(benchmarkSeries.timestamps.map((ts, index) => [ts, benchmarkSeries.close[index]])); const snapshotMap = new Map<number, Map<string, RrgAsset>>(); Object.entries(map).forEach(([ticker, label]) => { const series = dataset[ticker]; if (!series?.timestamps?.length) return; const points = series.timestamps.map((ts, index) => ({ ts, asset: series.close[index], benchmark: benchmarkClose.get(ts) })).filter((row): row is { ts: number; asset: number; benchmark: number } => Number.isFinite(row.asset) && Number.isFinite(row.benchmark) && row.benchmark !== 0); const ratios = points.map((row) => row.asset / row.benchmark); const rs = ratios.map((_, index) => { const fast = rollingMean(ratios, index, 10); const slow = rollingMean(ratios, index, 30); return fast === null || slow === null || slow === 0 ? null : 100 * (fast / slow); }); const rm = rs.map((value, index) => { if (value === null) return null; const windowValues = rs.slice(0, index + 1).slice(-9).filter((item): item is number => item !== null); const average = windowValues.length === 9 ? windowValues.reduce((sum, item) => sum + item, 0) / 9 : null; return average && average !== 0 ? 100 * (value / average) : null; }); points.forEach((row, index) => { if (rs[index] === null || rm[index] === null) return; if (!snapshotMap.has(row.ts)) snapshotMap.set(row.ts, new Map()); const tailIndexes: number[] = []; for (let tail = Math.max(0, index - 4); tail <= index; tail += 1) if (rs[tail] !== null && rm[tail] !== null) tailIndexes.push(tail); snapshotMap.get(row.ts)!.set(ticker, { ticker, label: metadata[ticker]?.name || label, points: tailIndexes.map((tail) => ({ x: rs[tail] as number, y: rm[tail] as number, ts: points[tail].ts })) }); }); }); return Array.from(snapshotMap.entries()).sort(([a], [b]) => a - b).map(([ts, assetMap]) => ({ ts, assets: Array.from(assetMap.values()) })).filter((snapshot) => snapshot.assets.length > 0); }
function toRows(series: MarketSeries | undefined, timestamps: number[]): MarketRow[] { if (!series) return []; const byTimestamp = new Map(series.timestamps.map((ts, index) => [ts, { ts, open: series.open[index], high: series.high[index], low: series.low[index], close: series.close[index] }])); return timestamps.map((ts) => byTimestamp.get(ts)).filter((row): row is MarketRow => !!row && [row.open, row.high, row.low, row.close].every(Number.isFinite)); }
async function loadMarketData(universe: UniverseKey, timeframe: TimeframeKey, signal: AbortSignal) { const map = universeMap(universe); const tickers = Array.from(new Set([...Object.keys(map), benchmarkFor(universe)])).join(","); const spec = TIMEFRAMES[timeframe]; const params = new URLSearchParams({ tickers, range: spec.range, interval: spec.interval }); const response = await fetch(`/.netlify/functions/market-data?${params.toString()}`, { signal }); if (!response.ok) throw new Error(`Market data request failed (${response.status})`); return (await response.json()) as { data: Dataset; metadata: Record<string, InstrumentMetadata>; fetchedAt: string }; }

function AppSelect({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="control-field"><span>{label}</span><span className="select-wrap"><select value={value} onChange={(event) => onChange(event.target.value)}>{children}</select><ChevronDown size={15} aria-hidden="true" /></span></label>; }
function Stat({ label, value, tone = "neutral", icon }: { label: string; value: string; tone?: "neutral" | "positive" | "warning"; icon: React.ReactNode }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div><span className="stat-label">{label}</span><strong>{value}</strong></div></div>; }

export default function Home() {
  const [universe, setUniverse] = useState<UniverseKey>("SECTORS");
  const [timeframe, setTimeframe] = useState<TimeframeKey>("1d");
  const [dataset, setDataset] = useState<Dataset>({});
  const [metadata, setMetadata] = useState<Record<string, InstrumentMetadata>>({});
  const [fetchedAt, setFetchedAt] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(-1);
  const [selectedTicker, setSelectedTicker] = useState("SPY");
  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState("");
  const [lastRefreshBucket, setLastRefreshBucket] = useState("");
  const requestRef = useRef<AbortController | null>(null);
  const benchmark = benchmarkFor(universe);
  const map = universeMap(universe);
  const benchmarkRows = useMemo(() => toRows(dataset[benchmark], dataset[benchmark]?.timestamps || []), [dataset, benchmark]);
  const safeIndex = benchmarkRows.length ? Math.min(Math.max(selectedIndex < 0 ? benchmarkRows.length - 1 : selectedIndex, 0), benchmarkRows.length - 1) : 0;
  const selectedBar = benchmarkRows[safeIndex];
  const snapshots = useMemo(() => buildSnapshots(dataset, universe, metadata), [dataset, universe, metadata]);
  const snapshot = useMemo(() => { if (!selectedBar) return undefined; return snapshots.reduce<Snapshot | undefined>((best, item) => item.ts <= selectedBar.ts ? item : best, undefined); }, [selectedBar, snapshots]);
  const availableTickers = [benchmark, ...Object.keys(map)].filter((ticker, index, all) => all.indexOf(ticker) === index);
  const detailTicker = availableTickers.includes(selectedTicker) ? selectedTicker : benchmark;
  const selectedRows = useMemo(() => toRows(dataset[detailTicker], benchmarkRows.map((row) => row.ts)), [dataset, detailTicker, benchmarkRows]);

  const load = async (scheduledBucket?: string) => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; setStatus("loading"); setError(""); try { const result = await loadMarketData(universe, timeframe, controller.signal); setDataset(result.data); setMetadata(result.metadata || {}); setFetchedAt(result.fetchedAt); setSelectedIndex(-1); setSelectedTicker(benchmarkFor(universe)); setLastRefreshBucket(scheduledBucket || refreshBucket(timeframe) || "manual"); setStatus("ready"); } catch (loadError) { if ((loadError as Error).name === "AbortError") return; setStatus("error"); setError(loadError instanceof Error ? loadError.message : "Unable to load market data"); } };
  useEffect(() => { void load(); return () => requestRef.current?.abort(); }, [universe, timeframe]);
  useEffect(() => { const timer = window.setInterval(() => { const bucket = refreshBucket(timeframe); if (bucket && bucket !== lastRefreshBucket && status !== "loading") void load(bucket); }, 1_000); return () => window.clearInterval(timer); }, [universe, timeframe, lastRefreshBucket, status]);

  const isOpen = (() => { const now = new Date(); const eastern = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hour: "numeric", minute: "numeric", hour12: false, weekday: "short" }).formatToParts(now); const hour = Number(eastern.find((part) => part.type === "hour")?.value || 0); const minute = Number(eastern.find((part) => part.type === "minute")?.value || 0); const weekday = eastern.find((part) => part.type === "weekday")?.value || ""; return !["Sat", "Sun"].includes(weekday) && (hour > 9 || (hour === 9 && minute >= 30)) && hour < 16; })();
  const chartLabel = universe === "SECTORS" ? "SECTOR LEADERSHIP" : universe === "INDUSTRIES" ? "INDUSTRY LEADERSHIP" : `${universe} HOLDINGS`;
  const selectTimestamp = (timestamp: number) => { const exactIndex = benchmarkRows.findIndex((row) => row.ts === timestamp); if (exactIndex >= 0) { setSelectedIndex(exactIndex); return; } let nearest = 0; benchmarkRows.forEach((row, index) => { if (row.ts <= timestamp) nearest = index; }); setSelectedIndex(nearest); };

  return <main className="dashboard-shell">
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark"><Activity size={21} strokeWidth={2.5} /></div><div><div className="eyebrow">MARKET INTELLIGENCE / 01</div><h1>Assets <span>Rotation</span></h1></div></div><div className="topbar-right"><div className="session-pill"><span className={`pulse-dot ${isOpen ? "live" : ""}`} />{isOpen ? "NY SESSION OPEN" : "NY SESSION CLOSED"}<small>{new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hour: "numeric", minute: "2-digit" }).format(new Date())} ET</small></div><button className="icon-button" title="Refresh data" onClick={() => void load()} disabled={status === "loading"}><RefreshCw size={17} className={status === "loading" ? "spin" : ""} /></button></div></header>
    <section className="hero-row"><div><div className="eyebrow accent">RELATIVE ROTATION GRAPH</div><h2>Read the market’s <em>next move.</em></h2><p className="lede">A live view of relative strength and momentum across the market. Every point is a signal; every tail is a story.</p></div><div className="hero-stamp"><Sparkles size={15} /><span>DATA WINDOW</span><strong>{TIMEFRAMES[timeframe].label}</strong></div></section>
    <section className="control-bar"><div className="control-group"><SlidersHorizontal size={16} /><span className="control-caption">VIEW</span><AppSelect label="Universe" value={universe} onChange={(value) => setUniverse(value as UniverseKey)}><option value="SECTORS">S&amp;P 500 sectors</option><option value="INDUSTRIES">Industry ETFs</option>{Object.entries(SECTOR_ETFS).map(([ticker, label]) => <option value={ticker} key={ticker}>{ticker} · {label} holdings</option>)}</AppSelect><AppSelect label="Timeframe" value={timeframe} onChange={(value) => setTimeframe(value as TimeframeKey)}>{Object.entries(TIMEFRAMES).map(([key, spec]) => <option value={key} key={key}>{spec.label}</option>)}</AppSelect></div><div className="control-meta"><span className="data-state"><Database size={14} /> {status === "ready" ? "Provider data connected" : status === "loading" ? "Syncing provider data" : "Provider unavailable"}</span><button className="refresh-button" onClick={() => void load()} disabled={status === "loading"}><RefreshCw size={14} /> Refresh</button></div></section>
    <section className="stats-row"><Stat label="BENCHMARK" value={`${benchmark} · ${metadata[benchmark]?.name || "S&P 500"}`} icon={<BarChart3 size={17} />} /><Stat label="VISIBLE ASSETS" value={`${snapshot?.assets.length || 0} / ${Object.keys(map).length}`} tone="positive" icon={<Layers3 size={17} />} /><Stat label="SELECTED CANDLE" value={selectedBar ? formatEastern(selectedBar.ts) : "Waiting for data"} icon={<Clock3 size={17} />} /><Stat label="FEED STATUS" value={status === "ready" ? "Live · cached 5m" : status === "loading" ? "Loading" : "Retry needed"} tone={status === "error" ? "warning" : "positive"} icon={<Wifi size={17} />} /></section>
    {status === "error" && <div className="error-banner"><X size={17} /><div><strong>Market data could not be loaded.</strong><span>{error}. The free Yahoo Finance endpoint can rate-limit requests; try Refresh in a moment.</span></div><button onClick={() => void load()}>Retry</button></div>}
    <section className="main-grid">
      <article className="chart-card rrg-card"><div className="card-heading"><div><div className="section-kicker"><span className="live-line" />RRG MAP / {chartLabel}</div><h3>Relative rotation</h3><p>Click a ticker to inspect its price action below.</p></div></div><div className="plot-wrap">{status === "loading" && <div className="chart-loading"><Loader2 className="spin" size={25} /><span>Fetching synchronized price history…</span></div>}{!snapshot && status !== "loading" && <div className="chart-loading"><Gauge size={24} /><span>RRG history is warming up for this timeframe.</span></div>}<RrgChart assets={snapshot?.assets || []} selectedTicker={detailTicker} onTickerSelect={setSelectedTicker} className="plot" /></div></article>
      <article className="chart-card benchmark-card"><div className="card-heading"><div><div className="section-kicker"><span className="live-line" />BENCHMARK / {benchmark}</div><h3>{metadata[benchmark]?.name || "Benchmark"}</h3><p>Same historical window and cursor as the RRG and selected ticker.</p></div><div className="detail-badge"><Download size={13} />OHLC · {TIMEFRAMES[timeframe].label}</div></div><div className="plot-wrap">{status === "loading" && <div className="chart-loading"><Loader2 className="spin" size={23} /><span>Loading benchmark history…</span></div>}<CandlestickChart ticker={benchmark} label={metadata[benchmark]?.name || "Benchmark"} rows={benchmarkRows} selectedIndex={safeIndex} selectedTimestamp={selectedBar?.ts} color={colors.ink} onCandleSelect={selectTimestamp} className="plot" /></div></article>
    </section>
    <div className="slider-row"><div className="slider-label"><span>HISTORICAL POSITION</span><strong>{selectedBar ? formatEasternLong(selectedBar.ts) : "—"}</strong></div><input type="range" min="0" max={Math.max(benchmarkRows.length - 1, 0)} value={safeIndex} onChange={(event) => setSelectedIndex(Number(event.target.value))} disabled={!benchmarkRows.length} /><div className="slider-endpoints"><span>{benchmarkRows[0] ? formatEastern(benchmarkRows[0].ts) : "—"}</span><span>{benchmarkRows.at(-1) ? formatEastern(benchmarkRows.at(-1)!.ts) : "—"}</span></div></div>
    <section className="chart-card detail-card"><div className="card-heading"><div><div className="section-kicker"><span className="live-line" />PRICE ACTION / {detailTicker}</div><h3>{detailTicker} candlestick detail</h3><p>{metadata[detailTicker]?.name || map[detailTicker] || "S&P 500 benchmark"} · {selectedBar ? `selected ${formatEasternLong(selectedBar.ts)}` : "waiting for data"}</p></div><div className="detail-badge"><Download size={13} />OHLC · {TIMEFRAMES[timeframe].label}</div></div><div className="plot-wrap detail-plot">{status === "loading" && <div className="chart-loading"><Loader2 className="spin" size={23} /><span>Loading price action…</span></div>}<CandlestickChart ticker={detailTicker} label={metadata[detailTicker]?.name || map[detailTicker] || "Benchmark"} rows={selectedRows} selectedIndex={safeIndex} selectedTimestamp={selectedBar?.ts} color={hashColor(detailTicker, universe)} onCandleSelect={selectTimestamp} className="plot" /></div></section>
    <footer className="footer"><span>ASSETS ROTATION <i />Built for focused market context</span><span>{fetchedAt ? `Provider sync · ${new Date(fetchedAt).toLocaleTimeString()}` : "Awaiting provider sync"}</span></footer>
  </main>;
}
